const CREATED_CODE = 201;
const BAD_REQUEST_CODE = 400;
const AUTH_ERROR_CODE = 401;
const FORBIDDEN_CODE = 403;
const NOT_FOUND_CODE = 404;
const DUPLICATE_KEY_ERROR = 409;
const INTERNAL_SERVER_ERROR = 500;

export default {
  CREATED_CODE,
  BAD_REQUEST_CODE,
  AUTH_ERROR_CODE,
  FORBIDDEN_CODE,
  NOT_FOUND_CODE,
  DUPLICATE_KEY_ERROR,
  INTERNAL_SERVER_ERROR,
};
