const CREATED_CODE: number = 201;
const BAD_REQUEST_CODE: number = 400;
const AUTH_ERROR_CODE: number = 401;
const FORBIDDEN_CODE: number = 403;
const NOT_FOUND_CODE: number = 404;
const DUPLICATE_KEY_ERROR: number = 409;
const INTERNAL_SERVER_ERROR: number = 500;

export default {
  CREATED_CODE,
  BAD_REQUEST_CODE,
  AUTH_ERROR_CODE,
  FORBIDDEN_CODE,
  NOT_FOUND_CODE,
  DUPLICATE_KEY_ERROR,
  INTERNAL_SERVER_ERROR,
};